# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dell/ov7670_in_out_final/ov7670_in_out_final.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
# IP: The module: 'design_1_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell/ov7670_in_out_final/ov7670_in_out_final.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dell/ov7670_in_out_final/ov7670_in_out_final.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Dell/ov7670_in_out_final/ov7670_in_out_final.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
# IP: The module: 'design_1_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dell/ov7670_in_out_final/ov7670_in_out_final.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dell/ov7670_in_out_final/ov7670_in_out_final.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
